apiVersion: apps/v1
kind: Deployment
metadata:
  name: fromdynaomodb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fromdynaomodb
  template:
    metadata:
      labels:
        app: fromdynaomodb
    spec:
      containers:
        - name: app
          image: gcr.io/fromdynaomodb/fromdynaomodb_image:v1
          imagePullPolicy: Always
