apiVersion: apps/v1
kind: Deployment
metadata:
  name: fromdynaomodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fromdynaomodb
  template:
    metadata:
      labels:
        app: fromdynaomodb
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
